declare namespace NodeJS {
  interface ProcessEnv {
    DATABASE_URL: string;
    NEXTAUTH_URL: string;
    NEXTAUTH_SECRET: string;
    YNAB_CLIENT_ID: string;
    YNAB_CLIENT_SECRET: string;
    CRON_SECRET?: string;
    USER_SYNC_MAX_REQUESTS?: string;
    USER_SYNC_WINDOW_SECONDS?: string;

    // Stripe
    STRIPE_SECRET_KEY: string;
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: string;
    STRIPE_WEBHOOK_SECRET: string;
    STRIPE_PRODUCT_ID?: string;

    // Stripe Price IDs (multi-currency - generated by setup-stripe-prices.ts)
    STRIPE_PRICE_MONTHLY?: string;
    STRIPE_PRICE_ANNUAL?: string;
  }
}
